export const OFFICIAL_SOURCES = [
  {
    id: "bd-rekenvoorschriften",
    authority: "Belastingdienst",
    title: "Rekenvoorschriften voor de geautomatiseerde loonadministratie",
    url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/themaoverstijgend/brochures_en_publicaties/rekenvoorschriften-voor-de-geautomatiseerde-loonadministratie",
    scope: "Loonheffingen, parameterwaarden en rekenregels",
  },
  {
    id: "bd-loonheffingen-nieuwsbrief",
    authority: "Belastingdienst",
    title: "Nieuwsbrief Loonheffingen",
    url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/themaoverstijgend/brochures_en_publicaties/nieuwsbrief-loonheffingen",
    scope: "Nieuwe regels en tarieven per jaar",
  },
  {
    id: "bd-box1-2026",
    authority: "Belastingdienst",
    title: "Box 1: uitleg en tarieven",
    url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/boxen_en_tarieven/box_1/box_1",
    scope: "Box 1 tarieven",
  },
  {
    id: "bd-ahk-2026",
    authority: "Belastingdienst",
    title: "Tabel algemene heffingskorting 2026",
    url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/heffingskortingen/algemene_heffingskorting/tabel-algemene-heffingskorting-2026",
    scope: "Algemene heffingskorting",
  },
  {
    id: "bd-arbeidskorting-2026",
    authority: "Belastingdienst",
    title: "Tabel arbeidskorting 2026",
    url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/heffingskortingen/arbeidskorting/tabel-arbeidskorting-2026",
    scope: "Arbeidskorting",
  },
  {
    id: "bd-iack-2026",
    authority: "Belastingdienst",
    title: "Tabel inkomensafhankelijke combinatiekorting 2026",
    url: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/heffingskortingen/inkomensafhankelijke_combikorting/inkomensafhankelijke-combinatiekorting-2026",
    scope: "IACK",
  },
  {
    id: "toeslagen-2026",
    authority: "Dienst Toeslagen",
    title: "Wat verandert er in 2026 voor uw toeslagen?",
    url: "https://www.belastingdienst.nl/wps/wcm/connect/nl/toeslagen-2026/topics/veranderingen-toeslagen-2026",
    scope: "Kinderopvangtoeslag en overige toeslagen",
  },
  {
    id: "rijksoverheid-kinderopvang",
    authority: "Rijksoverheid",
    title: "Kosten kinderopvang in Nederland",
    url: "https://www.rijksoverheid.nl/themas/belastingen-uitkeringen-en-toeslagen/kinderopvangtoeslag/kosten-kinderopvang-in-nederland",
    scope: "Maximum uurprijzen en systematiek kinderopvang",
  },
  {
    id: "svb-aow",
    authority: "SVB",
    title: "Bedragen AOW",
    url: "https://www.svb.nl/nl/aow/bedragen-aow/aow-bedragen",
    scope: "AOW bedragen; halfjaarlijkse updates",
  },
  {
    id: "svb-kinderbijslag",
    authority: "SVB",
    title: "Bedragen en betaaldagen kinderbijslag",
    url: "https://www.svb.nl/nl/kinderbijslag/bedragen-betaaldagen/bedragen-kinderbijslag.html",
    scope: "Kinderbijslagbedragen",
  },
];
